version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ROOT_PASSWORD: root
    steps:
      - checkout
      - run:
          name: lint
          command: ./gradlew lintKotlin
      - run:
          name: run migration
          command: ./gradlew flywayMigrate
      - run:
          name: generate jooq
          command: ./gradlew generateJooq
      - run:
          name: assemble
          command: ./gradlew assemble

workflows:
  version: 2
  build:
    jobs:
      - build
