version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ROOT_PASSWORD: root
    steps:
      - checkout
      - run:
          name: lint
          command: ./gradlew lintKotlin
      - run:
          name: perpare database
          command: |
            sudo apt update && sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u root -proot --execute="CREATE DATABASE IF NOT EXISTS stoneconvo_dev"
      - run:
          name: run migration
          command: ./gradlew flywayMigrate
      - run:
          name: generate jooq
          command: ./gradlew generateJooq
      - run:
          name: build
          command: ./gradlew build
  deploy:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run:
          name: deploy
          command: echo depolying
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
